<div class="buttons-set">
    <ul class="form-list">
        <li class="wide">
            <label for="ordercomment-comment"><?php echo $this->__('Order Comment') ?></label>
            <div class="input-box">
                <textarea id="ordercomment-comment" class="input-text validation-passed" name="ordercomment[comment]" title="<?php echo $this->__('Order Comment') ?>" rows="5" cols="10"></textarea>
            </div>
        </li>
    </ul>
</div>

<div id="onepage-checkout-ordercomment-additional-load"></div>

